axuesite/urls.py
from django.contrib import admin
from django.urls import path, include 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('post/<int:post_id>/', views.detail, name='detail'),
    path('paper/<int:paper_id>/', views.paper_download, name='paper_download')
]

blog/models.py
from django.db import models
import datetime
from django.utils import timezone
import os
# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=60)
    date_created = models.DateField(default=timezone.now)
    author = models.CharField(max_length=60, blank=True)
    main_text = models.TextField(blank=True)
    is_hidden = models.BooleanField(default=False)
    reference = models.ManyToManyField('Paper', related_name='contained_post', blank=True)
#   attached_file = models.FileField()
    def __str__(self):
        return self.title[:20]


def content_file_name(instance, filename):
    ext = filename.split('.')[-1] 
    filename = f'{instance.id}.{ext}'   
    return os.path.join('papers', filename)

class Paper(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100, blank=True)
    journal = models.CharField(max_length=100, blank=True)
    year = models.CharField(max_length=4, blank=True, default='')
    attachment = models.FileField(upload_to=content_file_name, blank=True)
    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Paper
from django.http import HttpResponse

def index(request):
    posts = Post.objects.filter(is_hidden=False)
    args = {'posts':posts}
    return render(request, 'blog/index.html', args)
    
def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    papers = post.reference.all()
    args = {'post':post, 'papers':papers}
    return render(request, 'blog/detail.html', args)

def paper_download(request, paper_id):
    paper = get_object_or_404(Paper, pk=paper_id)
    content = open(paper.attachment.path, 'rb') 
    resp = HttpResponse(content.read(), content_type='application/pdf')
    resp['Content-Disposition'] = 'inline; filename=' + paper.title + '.pdf'
    return resp

blog/templates/blog/detail.html
<!DOCTYPE html>
<html>
    {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
<head>
<title>PaperFun Detail</title>
</head>
<body>

<h1>PaperFun Official Website</h1>


<h2>{{ post.title }}</h2>
<h3>{{ post.author }}</h3>
<p>{{ post.main_text }}</p>

{% for paper in papers %}
<a href="{% url 'blog:paper_download' paper.id %}"">{{ paper.title }}</a><br>
{% endfor %}

<br>
<button><a href="{% url 'blog:index' %}"">Back</a></button>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
<head>
<title>PaperFun</title>
</head>
<body>

<h1>PaperFun Official Website</h1>


{% for post in posts %}
    <p><a href="{% url 'blog:detail' post.id %}">{{ post.title }}</a></p>
{% endfor %}

</body>
</html>